server:
  port: 8089

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservice-consumer-feign-8089 #自定义服务名称信息
    prefer-ip-address: true  #访问路径可以显示IP地址

spring:
  application:
    name: microservice-consumer-feign
  zipkin:
    base-url: http://localhost:9411


restUrlPrefix: http://localhost:8001

feign:
  hystrix:
    enabled: true