spring:
  application:
    name: microservice-zikpin
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 9411

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservice-zikpin-9411 #自定义服务名称信息
    prefer-ip-address: true  #访问路径可以显示IP地址

management:
  metrics:
    web:
      server:
        auto-time-requests: false