server:
  port: 9527

spring:
  application:
    name: microservice-zuul-gateway
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservice-zuul-9527 #自定义服务名称信息
    prefer-ip-address: true

zuul:
  prefix: /api         #多个统一前缀
  ignored-services: "*"  #原真实服务名忽略，多个用*
  routes:
    api.serviceId: microservice-consumer-feign
    api.path: /**




info:
  app.name: liang-zuul-microcloud
  company.name: www.liang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$